#define EE_HANDS
#define PREVENT_STUCK_MODIFIERS
#define IGNORE_MOD_TAP_INTERRUPT

#define USE_SERIAL_PD2

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 160
#define TAB_TIMER_TERM 500
#define RESET_THRESHOLD 1500

#undef PERMISSIVE_HOLD

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#if defined(ENCODER_ENABLE)
#define ENCODERS_PAD_A { F4 }
#define ENCODERS_PAD_B { F5 }
#define ENCODER_RESOLUTION 4
#endif
